dataset_name: "coco5k"
model_name: "ViT-B/16"

semantic_templates: "../template/openai_template.txt"

coco_root: "/data/datasets/coco2014"
used_dir: "val2014"
img_name_list_path: "../data/coco14/val_5k.txt"

attention_layers_to_use: [-4, -6]
attention_thr: 0.2

size: 336  # the shorter size used of the image

select_layer: -1

logit_scale: 50
score_threshold: 0.3
bkg_thre: 0.3
is_normalize: False

ignore_labels: [255]

# testing without sliding window
#sliding_crop_size: 0 # mIoU: 39.2(36.3)

# testing with sliding window
sliding_crop_size: 224 # mIoU: 40.0(37.5)