dataset_name: "voc21"
model_name: "ViT-B/16"

semantic_templates: "../template/car_template.txt"

label_dir: "/data/datasets/VOCdevkit/VOC2012/SegmentationClassAug"
voc12_root: "/data/datasets/VOCdevkit/VOC2012"
img_name_list_path: "../data/voc/val.txt"

attention_layers_to_use: [-4, -6]
attention_thr: 0.1

size: 336  # the shorter size used of the image

select_layer: -1

logit_scale: 100
score_threshold: 0.0
bkg_thre: 0.001
is_normalize: False

ignore_labels: [0, 255]

# testing without sliding window
sliding_crop_size: 0  #mIoU: 85.5(84.3)
# testing with sliding window
#sliding_crop_size: 336 #mIoU: 86.0(85.0)