dataset_name: "ade150"
model_name: "ViT-B/16"

semantic_templates: "../template/car_template.txt"

ade_root: "/Storage/personal/sunlin/datasets/ADEChallengeData2016"
used_dir: "validation"
img_name_list_path: "../data/ade/ade_val.txt"

attention_layers_to_use: [-4, -6]

logit_scale: 100
score_threshold: 0.3
bkg_thre: 0.3
is_normalize: False

ignore_labels: [0, 255]