dataset_name: "voc21"
model_name: "ViT-B/16"

semantic_templates: "../template/car_template.txt"

label_dir: "/Storage/personal/sunlin/datasets/VOCdevkit/VOC2012/SegmentationClassAug"
voc12_root: "/Storage/personal/sunlin/datasets/VOCdevkit/VOC2012"
img_name_list_path: "../data/voc/val.txt"

attention_layers_to_use: [-4, -6]

logit_scale: 100
score_threshold: 0.7
bkg_thre: 0.6
is_normalize: False
pr_cur_save_path: "../voc21_prc.png"

ignore_labels: [255]