dataset_name: "context"
model_name: "ViT-L/14"

semantic_templates: "../template/openai_template.txt"

label_dir: "/data/datasets/VOCdevkit/VOC2010/SegmentationClassContext"
voc12_root: "/data/datasets/VOCdevkit/VOC2010"
img_name_list_path: "../data/voc/context_val.txt"

attention_layers_to_use: [-4, -6]
attention_thr: 0.2

size: 336  # the shorter size used of the image

select_layer: -2

logit_scale: 50
score_threshold: 0.3
bkg_thre: 0.3
is_normalize: False

ignore_labels: [255]

# testing without sliding window
sliding_crop_size: 0 # mIoU: 39.0(34.8)

# testing with sliding window
# sliding_crop_size: 224  # mIoU: 39.5(35.7)
#score_threshold: 0.2
#bkg_thre: 0.2