dataset_name: "voc21"
model_name: "ViT-L/14"

semantic_templates: "../template/car_template.txt"

label_dir: "/Storage/personal/sunlin/datasets/VOCdevkit/VOC2012/SegmentationClassAug"
voc12_root: "/Storage/personal/sunlin/datasets/VOCdevkit/VOC2012"
img_name_list_path: "../data/voc/val.txt"

attention_layers_to_use: [-4, -6]

logit_scale: 50
score_threshold: 0.5
bkg_thre: 0
is_normalize: True

ignore_labels: [255]