dataset_name: "coco5k"
model_name: "ViT-L/14"

semantic_templates: "../template/openai_template.txt"

coco_root: "/Storage/personal/sunlin/datasets/coco2014"
used_dir: "val2014"
img_name_list_path: "../data/coco14/val_5k.txt"

attention_layers_to_use: [-4, -6]

logit_scale: 50
score_threshold: 0.5
bkg_thre: 0.5
is_normalize: False

ignore_labels: [255]