dataset_name: "context"
model_name: "ViT-L/14"

semantic_templates: "../template/car_template.txt"

label_dir: "/Storage/personal/sunlin/datasets/VOCdevkit/VOC2010/SegmentationClassContext"
voc12_root: "/Storage/personal/sunlin/datasets/VOCdevkit/VOC2010"
img_name_list_path: "../data/voc/context_val.txt"

attention_layers_to_use: [-4, -6]
logit_scale: 100
score_threshold: 0.45
bkg_thre: 0.45
is_normalize: False

ignore_labels: [0, 255]