dataset_name: "coco_stuff164"
model_name: "ViT-L/14"

semantic_templates: "../template/openai_template.txt"

coco_root: "/data/datasets/coco2017"
used_dir: "val2017"
img_name_list_path: "../data/coco14/coco_stuff164.txt"

attention_layers_to_use: [-4, -6]
attention_thr: 0.2

size: 336  # the shorter size used of the image

select_layer: -2

logit_scale: 50
score_threshold: 0.2
bkg_thre: 0.2
is_normalize: False

ignore_labels: [0, 255]

# testing without sliding window
sliding_crop_size: 0  # mIoU: 29.7(26.3)
# testing with sliding window
#sliding_crop_size: 224  # mIoU: 30.4(27.1)