dataset_name: "ade150"
model_name: "ViT-L/14"

semantic_templates: "../template/openai_template.txt"

ade_root: "/data/datasets/ADEChallengeData2016"
used_dir: "validation"
img_name_list_path: "../data/ade/ade_val.txt"

attention_layers_to_use: [-4, -6]
attention_thr: 0.2

size: 336  # the shorter size used of the image

select_layer: -1

logit_scale: 50
score_threshold: 0.2
bkg_thre: 0.2
is_normalize: False

ignore_labels: [0, 255]

# testing without sliding window
sliding_crop_size: 0  # mIoU: 24.5(22.1)
# testing with sliding window
#sliding_crop_size: 224  # mIoU: 25.0(22.9)